name: CI

on:
  push:

jobs:
  lint:
    name: Lint Jinja Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Run j2lint
        uses: ansible-actions/j2lint-action@v0.0.1
        with:
          target: "*.j2"

  sync:
    name: Netbox Sync
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: lint
    env:
      DATA_SOURCE_ID: "1"
    steps:
      - run: |
          curl https://netbox.freifunk-duesseldorf.de/api/core/data-sources/${DATA_SOURCE_ID}/sync/ \
            -X POST --fail \
            -H "Authorization: Token ${{ secrets.NETBOX_API_TOKEN }}"
