name: CI

on:
  push:

jobs:
  lint:
    name: Lint Jinja Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v6

      - name: Install j2lint
        run: pip install j2lint

      - name: Run j2lint
        run: |
          j2lint templates/*.j2 -w S6 --json > /tmp/lint.json || LINT_EXIT=$?
          jq -r '(.ERRORS | map(. + { type: "error" })) + (.WARNINGS | map(. + { type: "warning" })) | .[] | "::\(.type) file=\(.filename),line=\(.line_number),title=\(.id)::\(.message)"' < /tmp/lint.json
          exit $LINT_EXIT
